package forme;

import java.awt.BorderLayout;
import java.io.IOException;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import komunikacija.Komunikacija;
import transfer.TransferObjekatZahtev;
import util.Konstante;
import util.Util;

public class FrmGlavna extends javax.swing.JFrame {

    /**
     * Creates new form FrmGlavna
     */
    public FrmGlavna() {
        initComponents();
        this.setTitle("Glavni meni");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jmbGlavniMeni = new javax.swing.JMenuBar();
        jmUnos = new javax.swing.JMenu();
        jmiUnosKorisnika = new javax.swing.JMenuItem();
        jmiUnosFilmova = new javax.swing.JMenuItem();
        jmPretraga = new javax.swing.JMenu();
        jmiPretragaKorisnika = new javax.swing.JMenuItem();
        jmiPretragaFilmova = new javax.swing.JMenuItem();
        jmSistem = new javax.swing.JMenu();
        jmiOProgramu = new javax.swing.JMenuItem();
        jsepSistem = new javax.swing.JPopupMenu.Separator();
        jmiOdjava = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jmUnos.setText("Unos");

        jmiUnosKorisnika.setText("Unos korisnika");
        jmiUnosKorisnika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUnosKorisnikaActionPerformed(evt);
            }
        });
        jmUnos.add(jmiUnosKorisnika);

        jmiUnosFilmova.setText("Unos filmova");
        jmiUnosFilmova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUnosFilmovaActionPerformed(evt);
            }
        });
        jmUnos.add(jmiUnosFilmova);

        jmbGlavniMeni.add(jmUnos);

        jmPretraga.setText("Pretraga");

        jmiPretragaKorisnika.setText("Pretraga korisnika");
        jmiPretragaKorisnika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPretragaKorisnikaActionPerformed(evt);
            }
        });
        jmPretraga.add(jmiPretragaKorisnika);

        jmiPretragaFilmova.setText("Pretraga filmova");
        jmiPretragaFilmova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPretragaFilmovaActionPerformed(evt);
            }
        });
        jmPretraga.add(jmiPretragaFilmova);

        jmbGlavniMeni.add(jmPretraga);

        jmSistem.setText("Sistem");

        jmiOProgramu.setText("O programu");
        jmiOProgramu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiOProgramuActionPerformed(evt);
            }
        });
        jmSistem.add(jmiOProgramu);
        jmSistem.add(jsepSistem);

        jmiOdjava.setText("Odjava");
        jmiOdjava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiOdjavaActionPerformed(evt);
            }
        });
        jmSistem.add(jmiOdjava);

        jmbGlavniMeni.add(jmSistem);

        setJMenuBar(jmbGlavniMeni);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 341, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            TransferObjekatZahtev toz = new TransferObjekatZahtev();
            toz.setOperacija(Konstante.IZLOGUJ_ARHIVATORA);
            Komunikacija.getInstance().posaljiZahtev(toz);
            
            TransferObjekatZahtev toz1 = new TransferObjekatZahtev();
            toz1.setOperacija(Konstante.KRAJ_RADA);
            Komunikacija.getInstance().posaljiZahtev(toz1);
            
            Util.getInstance().clearUtil();
        } catch (IOException ioex) {
            ioex.printStackTrace();
        }

    }//GEN-LAST:event_formWindowClosing

    private void jmiUnosKorisnikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUnosKorisnikaActionPerformed
        JDialog d = new JDialog(this, "Unos korisnika");
        d.setLayout(new BorderLayout());
        PnlUnosKorisnika panel = new PnlUnosKorisnika();
        d.add(panel);
        d.pack();
        d.setLocationRelativeTo(this);
        d.setVisible(true);
    }//GEN-LAST:event_jmiUnosKorisnikaActionPerformed

    private void jmiPretragaKorisnikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPretragaKorisnikaActionPerformed
        JDialog d = new JDialog(this, "Pretraga korisnika");
        d.setLayout(new BorderLayout());
        PnlPretragaKorisnika panel = new PnlPretragaKorisnika();
        d.add(panel);
        d.pack();
        d.setLocationRelativeTo(this);
        d.setVisible(true);
    }//GEN-LAST:event_jmiPretragaKorisnikaActionPerformed

    private void jmiPretragaFilmovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPretragaFilmovaActionPerformed
        JDialog d = new JDialog(this, "Pretraga filmova");
        d.setLayout(new BorderLayout());
        PnlPretragaFilmova panel = new PnlPretragaFilmova(null);
        d.add(panel);
        d.pack();
        d.setLocationRelativeTo(this);
        d.setVisible(true);
    }//GEN-LAST:event_jmiPretragaFilmovaActionPerformed

    private void jmiUnosFilmovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUnosFilmovaActionPerformed
        JDialog d = new JDialog(this, "Unos filmova");
        d.setLayout(new BorderLayout());
        PnlUnosFilmova panel = new PnlUnosFilmova();
        d.add(panel);
        d.pack();
        d.setLocationRelativeTo(this);
        d.setVisible(true);
    }//GEN-LAST:event_jmiUnosFilmovaActionPerformed

    private void jmiOProgramuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiOProgramuActionPerformed
        JOptionPane.showMessageDialog(this, new PnlOProgramu(), "O programu", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jmiOProgramuActionPerformed

    private void jmiOdjavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiOdjavaActionPerformed
        try {
            TransferObjekatZahtev toz = new TransferObjekatZahtev();
            toz.setOperacija(Konstante.IZLOGUJ_ARHIVATORA);
            Komunikacija.getInstance().posaljiZahtev(toz);
            
            Util.getInstance().clearUtil();
            
            JOptionPane.showMessageDialog(this, "Uspešna odjava sa sistema.", "Sistemska poruka", JOptionPane.INFORMATION_MESSAGE);
            FrmLogin f = new FrmLogin();
            f.setVisible(true);
            this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Neuspešna odjava sa sistema.", "Sistemska poruka", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jmiOdjavaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmGlavna().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu jmPretraga;
    private javax.swing.JMenu jmSistem;
    private javax.swing.JMenu jmUnos;
    private javax.swing.JMenuBar jmbGlavniMeni;
    private javax.swing.JMenuItem jmiOProgramu;
    private javax.swing.JMenuItem jmiOdjava;
    private javax.swing.JMenuItem jmiPretragaFilmova;
    private javax.swing.JMenuItem jmiPretragaKorisnika;
    private javax.swing.JMenuItem jmiUnosFilmova;
    private javax.swing.JMenuItem jmiUnosKorisnika;
    private javax.swing.JPopupMenu.Separator jsepSistem;
    // End of variables declaration//GEN-END:variables
}
