package forme;

public class PnlOProgramu extends javax.swing.JPanel {

    /**
     * Creates new form PnlOProgramu
     */
    public PnlOProgramu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblOProgramu = new javax.swing.JLabel();

        jlblOProgramu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblOProgramu.setText("<html><p align=\"center\">Univerzitet u Beogradu<br>Fakultet Organizacionih nauka<br>Laboratorija za softversko inženjerstvo<br><br><br>Seminarski rad iz predmeta<br>Projektovanje softvera<br>Tema: Softverski sistem za praćenje <br>rada filmskog arhiva sa korisnicima<br><br><br>Profesor: dr Siniša Vlajić<br>Student: Vidan Dulanović 30/09/I<br><br>Beograd, 2016.</p></html>");
        jlblOProgramu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlblOProgramu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlblOProgramu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlblOProgramu;
    // End of variables declaration//GEN-END:variables
}
