package forme;

import domen.Korisnik;
import domen.Zaduzenje;
import forme.model.ZaduzenjeTableModel;
import java.awt.BorderLayout;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.TableColumn;
import util.Util;

public class PnlPrikazZaduzenja extends javax.swing.JPanel {

    private Korisnik k;

    /**
     * Creates new form PnlPrikazZaduzenja
     *
     * @param k
     */
    public PnlPrikazZaduzenja(Korisnik k) {
        initComponents();
        this.k = k;
        srediFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jlblNazivKorisnika = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblPrikazZaduzenja = new javax.swing.JTable();
        jbtnDodajZaduzenje = new javax.swing.JButton();
        jbtnIzmeniZaduzenje = new javax.swing.JButton();

        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });

        jLabel1.setText("Korisnik:");

        jtblPrikazZaduzenja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblPrikazZaduzenja);

        jbtnDodajZaduzenje.setText("Dodaj zaduženje");
        jbtnDodajZaduzenje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDodajZaduzenjeActionPerformed(evt);
            }
        });

        jbtnIzmeniZaduzenje.setText("Izmeni zaduženje");
        jbtnIzmeniZaduzenje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIzmeniZaduzenjeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnDodajZaduzenje)
                            .addComponent(jbtnIzmeniZaduzenje)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlblNazivKorisnika, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jlblNazivKorisnika, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnDodajZaduzenje)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnIzmeniZaduzenje)
                        .addGap(0, 223, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnDodajZaduzenjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDodajZaduzenjeActionPerformed
        PnlUnosZaduzenja p = new PnlUnosZaduzenja(k);
        JDialog d1 = (JDialog) SwingUtilities.getWindowAncestor(this);
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(d1);
        JDialog d = new JDialog(frame, "Unos novog zaduženja", true);
        d.setLayout(new BorderLayout());
        d.add(p, BorderLayout.CENTER);
        d.pack();
        d.setVisible(true);
    }//GEN-LAST:event_jbtnDodajZaduzenjeActionPerformed

    private void jbtnIzmeniZaduzenjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIzmeniZaduzenjeActionPerformed
        int red = jtblPrikazZaduzenja.getSelectedRow();
        if (red == -1) {
            JOptionPane.showMessageDialog(this, "Niste odabrali zaduženje!", "Sistemska poruka", JOptionPane.WARNING_MESSAGE);
        }
        ZaduzenjeTableModel model = (ZaduzenjeTableModel) jtblPrikazZaduzenja.getModel();
        Zaduzenje z = model.vratiZaduzenje(red);
        if (z.getDatumRazduzenja() != null && z.isVraceno() && z.getArhivatorRazduzio().getArhivatorID() != 1000) {
            JOptionPane.showMessageDialog(this, "Nije dozvoljeno menjati razdužena zaduženja!", "Sistemska poruka", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Util.getInstance().putZaduzenje("izabrano_zaduzenje", z);

        PnlUnosZaduzenja panel = new PnlUnosZaduzenja(k);
        panel.setPanel(this);
        JDialog d1 = (JDialog) SwingUtilities.getWindowAncestor(this);
        JFrame f = (JFrame) SwingUtilities.getWindowAncestor(d1);
        JDialog d = new JDialog(f, "Rad sa korisnikom: " + k.getNaziv(), true);
        d.setLayout(new BorderLayout());
        d.add(panel, BorderLayout.CENTER);
        d.pack();
        d.setLocationRelativeTo(this);
        d.setVisible(true);
    }//GEN-LAST:event_jbtnIzmeniZaduzenjeActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        srediFormu();
    }//GEN-LAST:event_formFocusGained

    private void srediFormu() {
        jlblNazivKorisnika.setText(k.getNaziv());
        ZaduzenjeTableModel model = new ZaduzenjeTableModel(k.getListaZaduzenja());
        jtblPrikazZaduzenja.setModel(model);

        TableColumn tc0 = jtblPrikazZaduzenja.getColumnModel().getColumn(0);
        tc0.setPreferredWidth(65);
        TableColumn tc1 = jtblPrikazZaduzenja.getColumnModel().getColumn(1);
        tc1.setPreferredWidth(65);
        TableColumn tc2 = jtblPrikazZaduzenja.getColumnModel().getColumn(2);
        tc2.setPreferredWidth(70);
        TableColumn tc3 = jtblPrikazZaduzenja.getColumnModel().getColumn(3);
        tc3.setPreferredWidth(40);
        TableColumn tc4 = jtblPrikazZaduzenja.getColumnModel().getColumn(4);
        tc4.setPreferredWidth(140);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnDodajZaduzenje;
    private javax.swing.JButton jbtnIzmeniZaduzenje;
    private javax.swing.JLabel jlblNazivKorisnika;
    private javax.swing.JTable jtblPrikazZaduzenja;
    // End of variables declaration//GEN-END:variables
}
