package forme;

import domen.Arhivator;
import domen.Film;
import domen.Korisnik;
import domen.Zaduzenje;
import forme.model.ZaduzenjeNovoTableModel;
import java.awt.BorderLayout;
import java.awt.Color;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.TableColumn;
import komunikacija.Komunikacija;
import transfer.TransferObjekatOdgovor;
import transfer.TransferObjekatZahtev;
import util.Konstante;
import util.Util;

public class PnlUnosZaduzenja extends javax.swing.JPanel {

    private Korisnik k;
    private List<Integer> lista;
    private Film f;
    private DateFormat df = new SimpleDateFormat("dd.MM.yyyy");
    private PnlPrikazZaduzenja panel;

    public Film getF() {
        return f;
    }

    public void setF(Film f) {
        this.f = f;
    }

    public PnlPrikazZaduzenja getPanel() {
        return panel;
    }

    public void setPanel(PnlPrikazZaduzenja panel) {
        this.panel = panel;
    }

    /**
     * Creates new form PnlUnosZaduzenja
     *
     * @param k
     */
    public PnlUnosZaduzenja(Korisnik k) {
        initComponents();
        this.k = k;
        lista = new ArrayList<>();
        srediFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jlblNazivKorisnika = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtblZaduzenja = new javax.swing.JTable();
        jbtnSacuvajZaduzenja = new javax.swing.JButton();
        jpnlUnosZaduzenja = new javax.swing.JPanel();
        jtxtDatumZaduzenja = new javax.swing.JTextField();
        jbtnKreirajZaduzenje = new javax.swing.JButton();
        jtxtZaduzenjeID = new javax.swing.JTextField();
        jbtnIzborFilma = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jbtnDodajZaduzenje = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtxtArhivatorID = new javax.swing.JTextField();
        jtxtKorisnikID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtFilm = new javax.swing.JTextField();
        jpnlIzmenaZaduzenja = new javax.swing.JPanel();
        jbtnIzmeni = new javax.swing.JButton();
        jtxtUplata = new javax.swing.JTextField();
        jtxtDatumRazduzenja = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jbtnObrisi = new javax.swing.JButton();

        jLabel1.setText("Korisnik:");

        jtblZaduzenja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jtblZaduzenja);

        jbtnSacuvajZaduzenja.setText("Sačuvaj zaduženja");
        jbtnSacuvajZaduzenja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSacuvajZaduzenjaActionPerformed(evt);
            }
        });

        jpnlUnosZaduzenja.setBorder(javax.swing.BorderFactory.createTitledBorder("Unos zaduženja"));

        jtxtDatumZaduzenja.setEditable(false);

        jbtnKreirajZaduzenje.setText("Kreiraj zaduženje");
        jbtnKreirajZaduzenje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKreirajZaduzenjeActionPerformed(evt);
            }
        });

        jtxtZaduzenjeID.setEditable(false);

        jbtnIzborFilma.setText("Izbor filma");
        jbtnIzborFilma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIzborFilmaActionPerformed(evt);
            }
        });

        jLabel3.setText("ZaduženjeID:");

        jbtnDodajZaduzenje.setText("Dodaj zaduženje");
        jbtnDodajZaduzenje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDodajZaduzenjeActionPerformed(evt);
            }
        });

        jLabel2.setText("KorisnikID:");

        jLabel5.setText("ArhivatorID:");

        jtxtArhivatorID.setEditable(false);

        jtxtKorisnikID.setEditable(false);

        jLabel4.setText("Datum zaduženja:");

        jtxtFilm.setEditable(false);

        javax.swing.GroupLayout jpnlUnosZaduzenjaLayout = new javax.swing.GroupLayout(jpnlUnosZaduzenja);
        jpnlUnosZaduzenja.setLayout(jpnlUnosZaduzenjaLayout);
        jpnlUnosZaduzenjaLayout.setHorizontalGroup(
            jpnlUnosZaduzenjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlUnosZaduzenjaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnlUnosZaduzenjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnlUnosZaduzenjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlUnosZaduzenjaLayout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                        .addGroup(jpnlUnosZaduzenjaLayout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(37, 37, 37)))
                    .addGroup(jpnlUnosZaduzenjaLayout.createSequentialGroup()
                        .addGroup(jpnlUnosZaduzenjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jbtnIzborFilma))
                        .addGap(14, 14, 14)))
                .addGroup(jpnlUnosZaduzenjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtKorisnikID, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtZaduzenjeID, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnKreirajZaduzenje)
                    .addComponent(jtxtFilm)
                    .addComponent(jtxtDatumZaduzenja)
                    .addComponent(jtxtArhivatorID, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnDodajZaduzenje))
                .addContainerGap())
        );
        jpnlUnosZaduzenjaLayout.setVerticalGroup(
            jpnlUnosZaduzenjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlUnosZaduzenjaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtnKreirajZaduzenje)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnlUnosZaduzenjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtKorisnikID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnlUnosZaduzenjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtZaduzenjeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnlUnosZaduzenjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtxtDatumZaduzenja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnlUnosZaduzenjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtxtArhivatorID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnlUnosZaduzenjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnIzborFilma)
                    .addComponent(jtxtFilm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnDodajZaduzenje)
                .addContainerGap())
        );

        jpnlIzmenaZaduzenja.setBorder(javax.swing.BorderFactory.createTitledBorder("Izmena zaduženja"));

        jbtnIzmeni.setText("Izmeni");
        jbtnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIzmeniActionPerformed(evt);
            }
        });

        jtxtUplata.setEditable(false);

        jtxtDatumRazduzenja.setEditable(false);

        jLabel7.setText("Uplata:");

        jLabel6.setText("Datum razduženja:");

        javax.swing.GroupLayout jpnlIzmenaZaduzenjaLayout = new javax.swing.GroupLayout(jpnlIzmenaZaduzenja);
        jpnlIzmenaZaduzenja.setLayout(jpnlIzmenaZaduzenjaLayout);
        jpnlIzmenaZaduzenjaLayout.setHorizontalGroup(
            jpnlIzmenaZaduzenjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlIzmenaZaduzenjaLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jbtnIzmeni)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jpnlIzmenaZaduzenjaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnlIzmenaZaduzenjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlIzmenaZaduzenjaLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtxtUplata, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlIzmenaZaduzenjaLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(jtxtDatumRazduzenja, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jpnlIzmenaZaduzenjaLayout.setVerticalGroup(
            jpnlIzmenaZaduzenjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlIzmenaZaduzenjaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpnlIzmenaZaduzenjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtDatumRazduzenja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnlIzmenaZaduzenjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtUplata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(40, 40, 40)
                .addComponent(jbtnIzmeni)
                .addGap(11, 11, 11))
        );

        jbtnObrisi.setText("Obriši");
        jbtnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnObrisiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlblNazivKorisnika, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnSacuvajZaduzenja)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnObrisi))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpnlUnosZaduzenja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jpnlIzmenaZaduzenja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jlblNazivKorisnika, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpnlIzmenaZaduzenja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnlUnosZaduzenja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnSacuvajZaduzenja)
                    .addComponent(jbtnObrisi))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnKreirajZaduzenjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnKreirajZaduzenjeActionPerformed
        try {
            TransferObjekatZahtev toz = new TransferObjekatZahtev();
            toz.setOperacija(Konstante.KREIRAJ_ZADUZENJE);
            Komunikacija.getInstance().posaljiZahtev(toz);
            TransferObjekatOdgovor too = Komunikacija.getInstance().primiOdgovor();
            int id = (int) too.getRezultat();

            for (int i : lista) {
                if (id == i) {
                    id++;
                }
            }
            lista.add(id);

            jtxtKorisnikID.setText(String.valueOf(k.getKorisnikID()));
            jtxtZaduzenjeID.setText(String.valueOf(id));
            jtxtDatumZaduzenja.setText(df.format(new Date()));
            int arhivatorID = Util.getInstance().getArhivator().getArhivatorID();
            jtxtArhivatorID.setText(String.valueOf(arhivatorID));
            jbtnDodajZaduzenje.setEnabled(true);
            jbtnIzborFilma.setEnabled(true);
            jbtnKreirajZaduzenje.setEnabled(false);

            JOptionPane.showMessageDialog(this, "Sistem je kreirao novo zaduženje.", "Sistemska poruka", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne može da kreira novo zaduženje.", "Sistemska poruka", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jbtnKreirajZaduzenjeActionPerformed

    private void jbtnIzborFilmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIzborFilmaActionPerformed
        PnlPretragaFilmova p = new PnlPretragaFilmova(this);
        JDialog d1 = (JDialog) SwingUtilities.getWindowAncestor(this);
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(d1);
        JDialog d = new JDialog(frame, "Izbor filma", true);
        d.setLayout(new BorderLayout());
        d.add(p, BorderLayout.CENTER);
        d.pack();
        d.setVisible(true);
    }//GEN-LAST:event_jbtnIzborFilmaActionPerformed

    private void jbtnDodajZaduzenjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDodajZaduzenjeActionPerformed
        try {
            if (jtxtFilm.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Niste izabrali film!", "Sistemska poruka", JOptionPane.ERROR_MESSAGE);
                jtxtFilm.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
                return;
            }

            int zaduzenjeID = Integer.parseInt(jtxtZaduzenjeID.getText());
            Date datumZaduzenja = df.parse(jtxtDatumZaduzenja.getText());
            Arhivator a = Util.getInstance().getArhivator();

            Zaduzenje z = new Zaduzenje(k, zaduzenjeID, datumZaduzenja, null, false, 0, f, a, null);
            ZaduzenjeNovoTableModel model = (ZaduzenjeNovoTableModel) jtblZaduzenja.getModel();
            model.dodajRed(z);
            jbtnDodajZaduzenje.setEnabled(false);
            jbtnKreirajZaduzenje.setEnabled(true);

            jtxtKorisnikID.setText("");
            jtxtZaduzenjeID.setText("");
            jtxtDatumZaduzenja.setText("");
            jtxtArhivatorID.setText("");
            jtxtFilm.setText("");
        } catch (ParseException pex) {
            pex.printStackTrace();
        }

    }//GEN-LAST:event_jbtnDodajZaduzenjeActionPerformed

    private void jbtnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIzmeniActionPerformed
        try {
            Zaduzenje z = Util.getInstance().getZaduzenje("izabrano_zaduzenje");
            Arhivator aR = Util.getInstance().getArhivator();
            Date datumRazduzenja = df.parse(jtxtDatumRazduzenja.getText());
            z.setDatumRazduzenja(datumRazduzenja);
            z.setArhivatorRazduzio(aR);
            z.setVraceno(true);
            z.setUplata(Double.parseDouble(jtxtUplata.getText()));

            TransferObjekatZahtev toz = new TransferObjekatZahtev();
            toz.setOperacija(Konstante.IZMENI_ZADUZENJE);
            toz.setParametar(z);
            Komunikacija.getInstance().posaljiZahtev(toz);
            TransferObjekatOdgovor too = Komunikacija.getInstance().primiOdgovor();

            panel.repaint();
            jbtnIzmeni.setEnabled(false);
            Util.getInstance().removeZaduzenje("izabrano_zaduzenje");
            
            JOptionPane.showMessageDialog(this, "Sistem je zapamtio zaduženje.", "Sistemska poruka", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne može da zapamti zaduženje.", "Sistemska poruka", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jbtnIzmeniActionPerformed

    private void jbtnSacuvajZaduzenjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSacuvajZaduzenjaActionPerformed
        try {
            ZaduzenjeNovoTableModel model = (ZaduzenjeNovoTableModel) jtblZaduzenja.getModel();
            List<Zaduzenje> listaZaduzenja = model.vratiListu();

            if (listaZaduzenja.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Niste uneli nijedno zaduženje!", "Sistemska poruka", JOptionPane.ERROR_MESSAGE);
                return;
            }

            TransferObjekatZahtev toz = new TransferObjekatZahtev();
            toz.setOperacija(Konstante.ZAPAMTI_ZADUZENJA);
            toz.setParametar(listaZaduzenja);
            Komunikacija.getInstance().posaljiZahtev(toz);
            TransferObjekatOdgovor too = Komunikacija.getInstance().primiOdgovor();

            model.obrisiListu();
            
            JOptionPane.showMessageDialog(this, "Sistem je zapamtio novo zaduženje.", "Sistemska poruka", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne može da zapamti novo zaduženje.", "Sistemska poruka", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jbtnSacuvajZaduzenjaActionPerformed

    private void jbtnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnObrisiActionPerformed
        int red = jtblZaduzenja.getSelectedRow();
        if (red == -1) {
            JOptionPane.showMessageDialog(this, "Niste odabrali zaduženje!", "Sistemska poruka", JOptionPane.WARNING_MESSAGE);
        }

        ZaduzenjeNovoTableModel model = (ZaduzenjeNovoTableModel) jtblZaduzenja.getModel();
        model.obrisiRed(red);
    }//GEN-LAST:event_jbtnObrisiActionPerformed

    private void srediFormu() {
        jpnlIzmenaZaduzenja.setVisible(false);
        jbtnDodajZaduzenje.setEnabled(false);
        jbtnIzborFilma.setEnabled(false);
        jlblNazivKorisnika.setText(k.getNaziv());

        List<Zaduzenje> lista = new ArrayList<>();
        ZaduzenjeNovoTableModel model = new ZaduzenjeNovoTableModel(lista);
        jtblZaduzenja.setModel(model);

        TableColumn tc0 = jtblZaduzenja.getColumnModel().getColumn(0);
        tc0.setPreferredWidth(200);
        TableColumn tc1 = jtblZaduzenja.getColumnModel().getColumn(1);
        tc1.setPreferredWidth(65);
        TableColumn tc2 = jtblZaduzenja.getColumnModel().getColumn(2);
        tc2.setPreferredWidth(140);
        TableColumn tc3 = jtblZaduzenja.getColumnModel().getColumn(3);
        tc3.setPreferredWidth(80);

        Zaduzenje z = Util.getInstance().getZaduzenje("izabrano_zaduzenje");

        if (z != null) {
            jpnlIzmenaZaduzenja.setVisible(true);
            jbtnKreirajZaduzenje.setEnabled(false);
            jbtnIzborFilma.setEnabled(false);
            jbtnDodajZaduzenje.setEnabled(false);

            jtxtKorisnikID.setText(String.valueOf(z.getKorisnik().getKorisnikID()));
            jtxtZaduzenjeID.setText(String.valueOf(z.getZaduzenjeID()));
            jtxtDatumZaduzenja.setText(df.format(z.getDatumZaduzenja()));
            jtxtArhivatorID.setText(String.valueOf(z.getArhivatorZaduzio().getArhivatorID()));
            jtxtFilm.setText(z.getFilm().getNaziv());
            jtxtDatumRazduzenja.setText(df.format(new Date()));
            jtxtUplata.setText(String.valueOf(izracunajUplatu()));
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtnDodajZaduzenje;
    private javax.swing.JButton jbtnIzborFilma;
    private javax.swing.JButton jbtnIzmeni;
    private javax.swing.JButton jbtnKreirajZaduzenje;
    private javax.swing.JButton jbtnObrisi;
    private javax.swing.JButton jbtnSacuvajZaduzenja;
    private javax.swing.JLabel jlblNazivKorisnika;
    private javax.swing.JPanel jpnlIzmenaZaduzenja;
    private javax.swing.JPanel jpnlUnosZaduzenja;
    private javax.swing.JTable jtblZaduzenja;
    private javax.swing.JTextField jtxtArhivatorID;
    private javax.swing.JTextField jtxtDatumRazduzenja;
    private javax.swing.JTextField jtxtDatumZaduzenja;
    public javax.swing.JTextField jtxtFilm;
    private javax.swing.JTextField jtxtKorisnikID;
    private javax.swing.JTextField jtxtUplata;
    private javax.swing.JTextField jtxtZaduzenjeID;
    // End of variables declaration//GEN-END:variables

    private double izracunajUplatu() {
        double uplata = 0;
        try {
            Date datumZaduzenja = df.parse(jtxtDatumZaduzenja.getText());
            Date datumRazduzenja = df.parse(jtxtDatumRazduzenja.getText());
            Calendar c1 = Calendar.getInstance();
            Calendar c2 = Calendar.getInstance();
            c1.setTime(datumZaduzenja);
            c2.setTime(datumRazduzenja);

            int brojRadnihDana = 0;
            int brojNeradnihDana = 0;

            while (c1.before(c2)) {
                if (Calendar.SATURDAY != c1.get(Calendar.DAY_OF_WEEK) && Calendar.SUNDAY != c1.get(Calendar.DAY_OF_WEEK)) {
                    brojRadnihDana++;
                } else {
                    brojNeradnihDana++;
                }
                c1.add(Calendar.DATE, 1);
            }

            uplata = brojRadnihDana * 750.0 + brojNeradnihDana * 850.0;
        } catch (ParseException pex) {
            pex.printStackTrace();
        }
        return uplata;
    }
}
